---
title: "Data Preparation"
output: html_document
execute: 
  freeze: true
# redirect output to another folder (default is base_dir/output)
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = fs::path(here::here(), "output"),
      ...
    )
  })
---

```{r setup, include=FALSE}
library(targets)
knitr::opts_chunk$set(echo = TRUE, tar_interactive = FALSE)
targets::tar_unscript()
```

```{targets utils, tar_globals=TRUE, include=FALSE}
check_used_mouse <- function(raw_parsed) {
  if (!has_name(raw_parsed, "device")) {
    return(TRUE)
  }
  raw_parsed$device |>
    str_c(collapse = "-") |>
    str_split("-") |>
    map_lgl(~ any(.x == "mouse"))
}
check_version <- function(raw_parsed, game_name) {
  if (game_name == "各得其所") {
    return(has_name(raw_parsed, "minmove"))
  }
  if (game_name == "小狗回家") {
    return(has_name(raw_parsed, "escortscore"))
  }
  if (game_name %in% c("格子卡片", "美术卡片", "数字卡片", "文字卡片")) {
    return(any(raw_parsed$type == "lure"))
  }
  return(TRUE)
}
validate_raw_parsed <- function(data_parsed, games_req_kb) {
  data_parsed |>
    mutate(
      valid_device = map2_lgl(
        raw_parsed, game_name,
        ~ !(check_used_mouse(.x) & .y %in% games_req_kb)
      ),
      valid_version = map2_lgl(
        raw_parsed, game_name,
        check_version
      ),
      valid = valid_device & valid_version
    )
}
clean_indices <- function(indices) {
  indices |>
    left_join(data.iquizoo::game_info, by = c("game_id", "game_name")) |>
    group_by(user_id, game_name) |>
    filter(
      if_else(
        str_detect(game_name_abbr, "[A|B]$"),
        row_number(desc(game_time)) == 1,
        row_number(desc(game_time)) <= 2
      )
    ) |>
    ungroup() |>
    mutate(
      indices_longer = map(
        indices,
        ~ pivot_longer(
          .x,
          cols = everything(),
          names_to = "index_name",
          values_to = "score"
        )
      ),
      .keep = "unused"
    ) |>
    unnest(indices_longer) |>
    group_by(user_id, game_name_abbr, game_name, game_version, index_name) |>
    mutate(
      occasion = case_when(
        str_detect(game_name_abbr, "A$") ~ "test",
        str_detect(game_name_abbr, "B$") ~ "retest",
        row_number(game_time) == 1 ~ "test",
        TRUE ~ "retest"
      ) |>
        factor(c("test", "retest"))
    ) |>
    ungroup() |>
    mutate(across(starts_with("game_name"), ~ str_remove(.x, "[A|B]$"))) |>
    pivot_wider(
      id_cols = c(user_id, game_name, game_name_abbr, game_version, index_name),
      names_from = occasion,
      values_from = score
    )
}
clean_indices_halves <- function(indices) {
  indices |>
    left_join(data.iquizoo::game_info, by = c("game_id", "game_name")) |>
    group_by(user_id, game_name) |>
    filter(
      if_else(
        str_detect(game_name_abbr, "[A|B]$"),
        row_number(desc(game_time)) == 1,
        row_number(desc(game_time)) <= 2
      )
    ) |>
    ungroup() |>
    mutate(
      indices_longer = map(
        indices,
        ~ pivot_longer(
          .x,
          cols = everything(),
          names_to = "index_name",
          values_to = "score"
        )
      ),
      .keep = "unused"
    ) |>
    unnest(indices_longer) |>
    group_by(user_id, game_name_abbr, game_name, game_version, index_name) |>
    mutate(
      occasion = recode_factor(
        row_number(game_time),
        `1` = "test",
        `2` = "retest"
      )
    ) |>
    ungroup() |>
    pivot_wider(
      id_cols = c(user_id, game_name, game_name_abbr, game_version, index_name),
      names_from = occasion,
      values_from = score
    )
}
```

```{targets set-globals, tar_globals=TRUE, include=FALSE}
future::plan(future.callr::callr)
tar_option_set(
  package = c("tidyverse", "preproc.iquizoo", "tarflow.iquizoo"),
  format = "qs",
  imports = "preproc.iquizoo"
)
games <- tarflow.iquizoo::search_games_mem(config::get("where"))
targets_data <- tarchetypes::tar_map(
  values = games,
  names = game_name_abbr,
  # major targets
  tar_target(data, pickup(query_tmpl_data, config_where_single_game)),
  tar_target(data_parsed, wrangle_data(data)),
  tar_target(
    data_valid,
    semi_join(data_parsed, filter(raw_validation, valid))
  ),
  tar_target(
    indices,
    preproc_data(data_valid, prep_fun, .input = input, .extra = extra)
  ),
  tar_target(
    data_valid_even,
    data_valid |>
      mutate(raw_parsed = map(raw_parsed, ~ slice(., seq(2, n(), 2))))
  ),
  tar_target(
    data_valid_odd,
    data_valid |>
      mutate(raw_parsed = map(raw_parsed, ~ slice(., seq(1, n(), 2))))
  ),
  tar_target(
    indices_even,
    preproc_data(data_valid_even, prep_fun, .input = input, .extra = extra)
  ),
  tar_target(
    indices_odd,
    preproc_data(data_valid_odd, prep_fun, .input = input, .extra = extra)
  ),
  # configurations
  tar_target(
    config_where_single_game,
    insert_where_single_game(config_where, game_id)
  ),
  tar_target(raw_validation, validate_raw_parsed(data_parsed, games_req_kb))
)
```

```{targets load-config, include=FALSE}
list(
  tar_target(file_config, "config.yml", format = "file"),
  tar_target(config_where, config::get("where", file = file_config)),
  tar_target(games_req_kb, config::get("require_keyboard", file = file_config))
)
```

```{targets download-users, include=FALSE}
list(
  tar_target(query_tmpl_users, fs::path("sql", "users.tmpl.sql"), format = "file"),
  tar_target(users, tarflow.iquizoo::pickup(query_tmpl_users, config_where))
)
```

```{targets data-and-scores, include=FALSE}
list(
  tar_target(query_tmpl_data, fs::path("sql", "data.tmpl.sql"), format = "file"),
  targets_data,
  tarchetypes::tar_combine(
    data_valid,
    targets_data[[3]]
  ),
  tarchetypes::tar_combine(
    indices,
    targets_data[[4]]
  ),
  tarchetypes::tar_combine(
    indices_even,
    targets_data[[7]]
  ),
  tarchetypes::tar_combine(
    indices_odd,
    targets_data[[8]]
  ),
  tar_target(indices_clean, clean_indices(indices)),
  tar_target(indices_clean_even, clean_indices_halves(indices_even)),
  tar_target(indices_clean_odd, clean_indices_halves(indices_odd))
)
```

```{targets reliabilty, include=FALSE}
list(
  tar_target(
    exclude_thu,
    c("图形推理A", "三维心理旋转A", "图形折叠A")
  ),
  tar_target(
    only_thu,
    c("数字推理", "文字推理", "数字推理A", "数字推理B", "文字推理A", "文字推理B")
  ),
  tar_target(
    item_keys,
    tarflow.iquizoo::pickup(
      "SELECT *
      FROM iquizoo_content_db.primarykey_question"
    ) |>
      mutate(NewId = bit64::as.character.integer64(NewId))
  ),
  tar_target(
    data_valid_final,
    data_valid |>
      group_by(game_name) |>
      filter(game_version == max(game_version)) |>
      ungroup()
  ),
  tar_target(
    indices_final,
    indices_clean |>
      left_join(users, by = "user_id") |>
      filter(
        !(game_name %in% exclude_thu & school == "清华大学认知实验") |
          (game_name %in% only_thu & school == "清华大学认知实验")
      ) |>
      group_by(game_name) |>
      filter(game_version == max(game_version)) |>
      ungroup()
  ),
  tar_target(
    indices_even_final,
    indices_clean_even |>
      group_by(game_name) |>
      filter(game_version == max(game_version)) |>
      ungroup()
  ),
  tar_target(
    indices_odd_final,
    indices_clean_odd |>
      group_by(game_name) |>
      filter(game_version == max(game_version)) |>
      ungroup()
  ),
  tarchetypes::tar_file_read(
    config_ic,
    here::here("config/internal-consistency.csv"),
    read_csv(!!.x, show_col_types = FALSE)
  ),
  tar_target(
    reliability_split_half,
    bind_rows(
      odd = indices_odd_final,
      even = indices_even_final,
      .id = "halves"
    ) |>
      semi_join(filter(config_ic, method == "prophecy"), by = "game_name") |>
      pivot_wider(
        id_cols = c(user_id, game_name, game_name_abbr, game_version, index_name),
        names_from = halves,
        values_from = test,
        names_prefix = "score_"
      ) |>
      group_by(game_name, game_name_abbr, game_version, index_name) |>
      summarise(
        n_split_half = sum(!is.na(score_odd) & !is.na(score_even)),
        r_split_half = cor(score_odd, score_even, use = "pairwise"),
        split_half = (2 * r_split_half) / (1 + r_split_half),
        .groups = "drop"
      ) |>
      drop_na() |>
      mutate(game_name_origin = game_name) |>
      mutate(
        across(
          c(game_name, game_name_abbr),
          ~ str_remove(., "[A|B]$")
        )
      )
  ),
  tar_target(
    reliability_alpha,
    data_valid_final |>
      semi_join(filter(config_ic, method == "alpha"), by = "game_name") |>
      # BNU source data were incorrect for these games
      left_join(users, by = "user_id") |>
      filter(
        !(game_name %in% exclude_thu & school == "清华大学认知实验") |
          (game_name %in% only_thu & school == "清华大学认知实验")
      ) |>
      # data from the last time of each test is deemed the right one
      left_join(data.iquizoo::game_info, by = c("game_id", "game_name")) |>
      group_by(user_id, game_name, game_version) |>
      filter(row_number(desc(game_time)) == 1) |>
      ungroup() |>
      unnest(raw_parsed) |>
      filter(acc != -1) |>
      mutate(
        block = if_else(
          block == 1,
          "prac", "test", ""
        )
      ) |>
      left_join(item_keys, by = c("itemid" = "Id")) |>
      mutate(itemid = coalesce(NewId, itemid)) |>
      group_by(user_id, game_id) |>
      mutate(item = row_number(itemid)) |>
      ungroup() |>
      group_by(game_name, game_name_abbr, game_version, block) |>
      group_modify(
        possibly(
         ~ . |>
          pivot_wider(
            id_cols = user_id,
            names_from = item,
            values_from = acc
          ) |>
          select(-user_id) |>
          psych::alpha(warnings = FALSE) |>
          pluck("total", "std.alpha") |>
          as_tibble_col(column_name = "alpha"),
          otherwise = tibble(alpha = NA_real_)
        )
      ) |>
      ungroup() |>
      mutate(game_name_origin = game_name) |>
      mutate(
        across(
          c(game_name, game_name_abbr),
          ~ str_remove(., "[A|B]$")
        )
      )
  ),
  tar_target(
    reliability_test_retest,
    indices_final |>
      filter(if_all(contains("test"), is.finite)) |>
      group_by(game_name, index_name) |>
      mutate(
        data.frame(test = test, retest = retest) |>
          performance::check_outliers(method = "mahalanobis") |>
          as_tibble()
      ) |>
      ungroup() |>
      group_by(game_name, game_name_abbr, game_version, index_name) |>
      group_modify(
        ~ tibble(
          n_test_retest = nrow(.x),
          n_no_outlier = .x |>
            filter(!Outlier) |>
            nrow(),
          icc = .x |>
            select(contains("test")) |>
            psych::ICC() |>
            pluck("results", "ICC", 2),
          icc_no_outlier = .x |>
            filter(!Outlier) |>
            select(contains("test")) |>
            psych::ICC() |>
            pluck("results", "ICC", 2),
          r_test_retest = cor(.x$test, .x$retest),
          r_test_retest_no_outlier = with(
            subset(.x, !Outlier),
            cor(test, retest)
          ),
          avg_test = mean(.x$test[!.x$Outlier], na.rm = TRUE),
          avg_retest = mean(.x$retest[!.x$Outlier], na.rm = TRUE),
          retest_change = .x |>
            filter(!Outlier) |>
            summarise(t.test(retest, test, paired = TRUE) |> broom::tidy()) |>
            rstatix::p_format() |>
            rstatix::p_mark_significant() |>
            mutate(
              summary_msg = str_glue("{round(estimate, 3)}({p.value})")
            ) |>
            pull(summary_msg)
        )
      ) |>
      ungroup()
  ),
  tar_target(
    reliability_test_retest_odd,
    indices_odd_final |>
      left_join(users, by = "user_id") |>
      filter(
        !(game_name %in% exclude_thu & school == "清华大学认知实验") |
          (game_name %in% only_thu & school == "清华大学认知实验")
      ) |>
      filter(if_all(contains("test"), is.finite)) |>
      group_by(game_name, game_name_abbr, game_version, index_name) |>
      mutate(
        data.frame(test = test, retest = retest) |>
          performance::check_outliers(method = "mahalanobis") |>
          as_tibble()
      ) |>
      group_modify(
        ~ tibble(
          icc_odd_half = .x |>
            filter(!Outlier) |>
            select(contains("test")) |>
            psych::ICC() |>
            pluck("results", "ICC", 2),
          r_odd_half = with(
            subset(.x, !Outlier),
            cor(test, retest)
          )
        )
      ) |>
      ungroup()
  ),
  tar_target(
    reliability,
    reliability_test_retest |>
      full_join(
        reliability_test_retest_odd,
        by = c("game_name", "game_name_abbr", "game_version", "index_name")
      ) |>
      full_join(
        bind_rows(reliability_split_half, reliability_alpha) |>
          mutate(index_name = coalesce(index_name, "nc")),
        by = c("game_name", "game_name_abbr", "game_version", "index_name")
      ) |>
      mutate(game_name_origin = coalesce(game_name_origin, game_name)) |>
      select(game_name_origin, everything())
  ),
  tar_target(
    file_reliability,
    writexl::write_xlsx(reliability, here::here("output/reliability.xlsx"))
  )
)
```

```{r run-pipeline, include=FALSE}
tar_make_future(workers = 20)
```
