default:
  where:
  - table: base_organization
    field: Name
    values:
    - 四川师范大学认知实验
    - 北京师范大学认知实验
    - 清华大学认知实验
  - table: v_organizationuser
    field: GradeName
    operator: REGEXP
    values: 2.+级
  require_keyboard:
  - 变色魔块PRO
  - 卡片分类PRO
  - 快速归类PRO
  - 一心二用PRO
  - 语义判断
  - 数字卡片
  - 美术卡片
  - 太空飞船PRO
  - 候鸟迁徙PRO
  - 专注大师_中级
  - 声调判断
  - 格子卡片
  - 文字卡片
  - 魔术师终极
  - 多彩文字PRO
  - 察颜观色PRO
  - 速算师（中级）
